- name: Configuring the Docker Container
  vars_prompt:
    - name: CNAME
      prompt: Enter The Name of Container You Want To Manage
      private: no
  hosts: localhost
  tasks:
    - name: Getting the IP of Container
      command: docker inspect --format='{%raw %}{{ .NetworkSettings.IPAddress }}{% endraw %}' '{{CNAME}}'
      register: IP
      
    - name: IP
      debug:
        var: IP.stdout

    - name: Inventory
      blockinfile:
        path: /etc/ansible/hosts
        block: |
          {{IP.stdout}} ansible_ssh_user=root ansible_ssh_pass=123
